### ISSUE TITLE
Being able to rename a contact

### ISSUE THREAD

**Issue by Rudy-Perrin** [redDwarf03/archethic_mobile_wallet#1019]
### Is your feature request related to a problem?

You cannot change the name of saved contacts.
We have to delete it and recreate it.

### Describe the solution you'd like

Add the ability to rename a contact from the address book.

**Comment by akheelnazim** [comment]
Can you assign it to me? I can give it a try.

**Comment by redDwarf03** [comment]
Until onchain contact management is in place, the address book function will be decommissioned.
