### ISSUE TITLE
Extension requires useless permissions

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#1051]
### Describe the problem you discovered

Extension uses "Read your browser history" permission.
This should not be.

<img width="247" alt="Capture d’écran 2024-07-25 à 18 36 22" src="https://github.com/user-attachments/assets/366df4a9-45b1-44f4-aa36-2bdd43093836">

**Comment by redDwarf03** [comment]
This permission comes from `chrome.tabs` usage
I wrote on `tabs` permission on extension store admin page: ```Used to manage tabs when opening new browser windows related to the wallet, to view transaction details, or to access trading platforms.```
For me, that's not an issue
