### ISSUE TITLE
Remove the inability to take screenshots

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1095]
in `android/app/src/main/java/net/archethic/archethic_wallet/MainActivityArchethicWallet.java` remove
```
   // Hides application preview (e.g. when switching between applications)
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);
```

This made it possible to block screenshots. 

NB: Check that application preview management is blocked when changing applications

**Comment by n0uki63** [comment]
Vote **Yes** for that (●'◡'●)
