### ISSUE TITLE
aeSwap in wallet - Bugs

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1120]
- [x] : Balances are not correctly updated after actions (swap)
- [x] : Add in control method a control of balance before use case calling
- [x] : If a smart contract meets an asynchrone error, wallet is not informed. So instead of directly display "... successfully executed" in the result sheet, display “Processing in progress” as long as processing has not been completed and the final amount retrieved

**Comment by Chralu** [comment]
Balance update fixed by  #1120
