### ISSUE TITLE
signTransaction does not handle Tx v3 format

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#1165]
### Describe the problem you discovered

Signing transactions through RPC does not handle TX v3 format.

Because of this, signing v3 transactions from libjs returns an 'Invalid format' error.

## v2 format

```ts
{
  type: String,
  version: int,
  data: {
    // ...
    recipients: List<String>
  }
}
```

## v3 format

```ts
{
  type: String,
  version: int,
  data: {
    // ...
    recipients: List<{
        action: String?,
        address: String?,
        args: List<{}>?
    }>
  }
}
```

### Describe the solution you'd like

There are multiple solutions.

1. accept v3 transactions only (acceptable because v2 isn't used anymore)
2. add an automatic v2 to v3 conversion when parsing RPC command

**Comment by redDwarf03** [comment]
And why we have `SignTransactionConfirmationFormState` naming in `send_transaction` rpc_command_receiver ?

**Comment by Chralu** [comment]
> And why we have `SignTransactionConfirmationFormState` naming in `send_transaction` rpc_command_receiver ?

This looks like a mistake 😓
