### ISSUE TITLE
Removing a wallet does not empty local data

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#1166]
### Describe the problem you discovered

On MacOS
 
1. Create a wallet named 'test' on testnet
2. take note of the wallet's address
3. Remove it from aeWallet
4. Re-create a wallet on testnet named 'test'

=> The wallet's address is the same as previous.

**Comment by redDwarf03** [comment]
The issue is not related to local data storage.
Hive boxes are correctly deleted when we delete the wallet from the menu.
The issue is related to the provider _AccountNotifier which is keep alived.
