### ISSUE TITLE
Restore Android 9 support

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#1167]
### Is your feature request related to a problem?

Android 9 has been evicted because of Webview advanced features support.
Those webview features are required to embed web DApps.

This removes support for 10% of the Android users, which is problematic.

### Describe the solution you'd like

We should only remove the embedded web DApp feature for Android < 10.

**Comment by redDwarf03** [comment]
fixed https://github.com/archethic-foundation/archethic-wallet/pull/1092
