### ISSUE TITLE
Create NFT - Timeout

### ISSUE THREAD

**Issue by cryptonythe** [redDwarf03/archethic_mobile_wallet#1197]
### Describe the problem you discovered

I encountered an error while creating NFT using Windows wallet. The wallet displayed a timeout after I confirmed the creation. Unaware that the first creation had been successfully processed by the blockchain, I made 3 additional attempts until I received a success message.

Unfortunately, this resulted in a creation of 4 NFT instead of a single one.

![Image](https://github.com/user-attachments/assets/df4ca457-4318-496c-97db-a8dcf9abfbce)
![Image](https://github.com/user-attachments/assets/e4c8a9ef-45d2-41f1-a272-a5b8b121c262)

### Describe the solution you'd like

Reverse the transaction or simply be aware that the NFT could have been created despite the error message

**Comment by redDwarf03** [comment]
this fix will be not fixed because NFT Creation feature has been removed from aeWallet 
https://github.com/archethic-foundation/archethic-wallet/pull/1205
