### ISSUE TITLE
Transactions disappear when user imports a wallet

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#190]
### Describe the problem you discovered

The keychain is found but tx don’t load
Check the last address of the tx chain next to the import

**Comment by n0uki63** [comment]
Lorsque l'on importe un portefeuille existant dans l'application, le système retrouve bien le compte a importé.
Le compte est alors importé mais son solde est **nul**. Ce compte possède alors une adresse publique différente de celle avant suppression et import.

Si quelqu'un envoie des fonds sur cette nouvelle adresse, le compte reçoit les fonds.

En cliquant sur le nom du compte, on retrouve le **compte initial** avec sa **valorisation avant suppression**. Le compte retrouve alors son **adresse publique d'origine**.

Par contre, les fonds qui ont été transmis sur la nouvelle adresse juste après import **disparaissent**.

Pourtant autant, si quelqu'un continue d'envoyer des fonds sur cette nouvelle adresse, il n'obtient pas de message d'erreur, mais les fonds aboutissent vers un compte inaccessible ?!
