### ISSUE TITLE
Add more APK informations

### ISSUE THREAD

**Issue by LucBerge** [redDwarf03/archethic_mobile_wallet#198]
### Is your feature request related to a problem?

It is not clear which apk a user must choose in the release section.

### Describe the solution you'd like

Add more informations about it, like the differencies between `arm64`, `armabi` and ×`86_64`.

**Comment by redDwarf03** [comment]
Hello
There are differente APK for   runtime compiled for [armeabi-v7a](https://developer.android.com/ndk/guides/abis#v7a) (ARM 32-bit), [arm64-v8a](https://developer.android.com/ndk/guides/abis#arm64-v8a) (ARM 64-bit), and [x86-64](https://developer.android.com/ndk/guides/abis#86-64) (x86 64-bit).
