### ISSUE TITLE
lock screen - bug with faceID

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#208]
### Describe the problem you discovered

Issue from Fabrice
"quand tu actives la détection faciale sur le téléphone pour le déverrouillage

et que tu possèdes aussi une empreinte

il priorise la détection faciale

si il ne reconnait pas le visage

alors il te propose l'empreinte

tu poses le doigt, l'empreinte est OK mais ca ne déverrouille pas"

**Comment by Chralu** [comment]
iOS devices have either FaceID or TouchID capability. 
There is no way to get both simultaneously.

So I don't know how to reproduce that issue.

**Comment by redDwarf03** [comment]
Fixed with 2.3.9
