### ISSUE TITLE
Loading without timeout

### ISSUE THREAD

**Issue by LucBerge** [redDwarf03/archethic_mobile_wallet#209]
### Describe the problem you discovered

I'm not able to create my wallet :
1. I save my private key
2. I enter my private key
3. I choose password authentication

After that, the app displays "Votre wallet est en cours de configuration..." forever. There is no timeout neither an error message displayed.

### Describe the solution you'd like

Add a timeout if the configuration or connection with the blockchain failed and display an error message.
- On wallet creation
- On wallet connection

Maybe the problem comes from my phone. It is old and my Android version as well...
- Orange Neva 80
- Android 6.0.1 (Latest version available on this phone)

The app is succesfully installed and respond correctly. If the Android version I use is the problem, make sure it is only possible to install the app for compatible Android versions.

**Comment by redDwarf03** [comment]
Hello
Thx for your feedback
could you give me the name of the account you created please

**Comment by LucBerge** [comment]
`WALLET_ARCHETHIC`

But I'm not even sure it has been created : When I try to connect to an existing wallet, I enter my secret phrase and the app tells me "No keychain exists for this secret phrase".

How can I acces the app logs ?
How can I send it to you ?

**Comment by LucBerge** [comment]
Ok I just tried with a tablet:
- Galaxy Tab S2
- Android 7.0

Loading forever as well (same wallet name).

The installed apk on both system is `v7-armabi`.

**Comment by redDwarf03** [comment]
could you send me your 24 words please by mail sylvain@uniris.io please

**Comment by LucBerge** [comment]
> could you send me your 24 words please by mail [sylvain@uniris.io](mailto:sylvain@uniris.io) please

I did. Check your spams

**Comment by redDwarf03** [comment]
Yes. I received it. Thanks but the mainnet has been restart next a major change last Thursday. So I’m sorry but your keychain and seed are not available now. Have you retest the app in the version 1.0.3 ?

**Comment by LucBerge** [comment]
Same problem. Can the location change the app behaviours ?

**Comment by LucBerge** [comment]
With the version 1.0.4 I have the following error:
`PhoenixException: socket closed`

The timeout issue is now solved. Should I open a new issue for this exception ?

Could the location be the problem ? I'm traveling in south america rigth now.

**Comment by redDwarf03** [comment]
I updated the bug bounty issue related to this issue.

**Comment by redDwarf03** [comment]
Hello @LucBerge . A new version 1.1.2 is available. Could you tell me if you have this issue again please

**Comment by LucBerge** [comment]
Same issue in 1.1.2
`Une erreur s'est produite. Essayer à nouveau plus tard (ko)`

**Comment by redDwarf03** [comment]
@LucBerge is it possible to discuss with discord or telegram please ?

**Comment by LucBerge** [comment]
Discord yes MrDomoo#0953

**Comment by redDwarf03** [comment]
@LucBerge , thank you. invitation sent
