### ISSUE TITLE
Samsung Smart Suggestion crash when entering text to send UCOs

### ISSUE THREAD

**Issue by Dractive** [redDwarf03/archethic_mobile_wallet#210]
### Describe the problem you discovered

When I'm trying to type text into the section "message (0/200)", an error appears and says "Samsung Smart Suggestion stops systematically". 

![Screenshot_20220720-133741](https://user-images.githubusercontent.com/109668108/179974677-9ef89164-83a6-4fbe-bf73-c47d6c9c6674.jpg)
.

After a few tries, I had the same issue in the section "Enter address".

![Screenshot_20220720-135923](https://user-images.githubusercontent.com/109668108/179976650-c728cbbe-6589-47c3-a46e-a7eb1b557ef3.jpg)

This error doesn't crash the wallet. I mean that if I cancel the warn, I can still type in and use the app.

**Additional information :** 

**Model of phone :** Galaxy XCover 4s
**Model number :** SM-G398FN/DS
**Wallet version :** 1.0.1

### Describe the solution you'd like

The solution should able the user to enter the destination address without any warning while entering it.

**Comment by redDwarf03** [comment]
hello. thanks for your feedback. i will investigate the source of this message

**Comment by redDwarf03** [comment]
i have used solution described here: https://github.com/flutter/flutter/issues/98505
To be tested in next version with @Dractive
