### ISSUE TITLE
Add a possibility to copy balances

### ISSUE THREAD

**Issue by elmaroufy** [redDwarf03/archethic_mobile_wallet#221]
### Is your feature request related to a problem?

Impossible to copy balances on wallet main screen 

### Describe the solution you'd like

Add a way to copy UCO balance and fiat balance on the main screen

### Additional context

macOS

**Comment by redDwarf03** [comment]
Hello. Do you want a copy/paste feature with the selection of the amount of the balance (fiat and crypto)? Could you explain a use case please to be sure? Thx

**Comment by elmaroufy** [comment]
Hello,
I want to copy the exact amount of my UCO balance and fiat balance, maybe with 
Right click > 
  - copy UCO Amount   
  - copy Fiat Amount
 Double click can copy by default UCO amount

![image](https://user-images.githubusercontent.com/7628780/180863916-917a27eb-62e3-4f44-83e2-298bae5c1a7c.png)

**Comment by redDwarf03** [comment]
available in the next version 1.0.4
