### ISSUE TITLE
Absinthe subscription is not finished when the transaction is sent

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#239]
### Describe the problem you discovered

Absinthe subscription is not finished when the transaction is sent
In this case, the suscription returns a maxConfirmations = 0

### Describe the solution you'd like

Send the transaction when the subscription is ok

**Comment by ghost** [comment]
See archethic-foundation/archethic-node#522

**Comment by redDwarf03** [comment]
version >= 1.1.0
