### ISSUE TITLE
Prevent user from jailbreak

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#289]
### Describe the solution you'd like

if user uses a jailbreak device, inform him 
use flutter_jailbreak_detection lib

**Comment by gdaguin** [comment]
Hello,

To solve this issue, I believe we can consider two scenarios:

- Checking if the currently used device is jailbroken, using the flutter_jailbreak_detection package.
- Verifying the installation source of the application (on Android and iOS), whether it comes from an official store (Google Play or Apple App Store) or not, using the install_referrer package. With this package, we can also check the application's package name to prevent it from being resigned by someone else who might tamper with the application and extract debug information.

In either case, what behavior is expected? We can either block the usage of the application (displaying a dedicated screen where the user can't proceed) or display an informative snackbar each time the application is launched.

**Comment by redDwarf03** [comment]
First, I'd like a message to inform the user of the application's execution conditions. So if the device is jailbroken or in debug mode or from an unofficial source, etc...

Either a popup with the user validating his understanding of the risks associated with his execution environment, or a banner.
Ideally, users should see the popup once and then the banner all the time their device is not compliant.
If he improves his security, the banner can disappear.
And if security is reduced again, the popup reappears once, followed by the banner. Etc....

Secondly, we'll provide later the user with a score linked to the security of the environment in which the user is using the wallet (the higher the score, the more secure the wallet).
Example: 
- the wallet will have a better score if it is protected by biometrics than by a pin code
- the wallet will score better if it's not on a jailbroken device
A matrix is to be created to define the scoring, but in a different outcome.

Note this piece of code in the comments, which doesn't work completely but can be reused: https://github.com/archethic-foundation/archethic-wallet/blob/43f124800be7e659b531657fa8851efe675cf8fd/lib/main.dart#L257

**Comment by gdaguin** [comment]
Ok copy that, that's clear.

On the Android part, the application is only available on the Google PlayStore or are you making it available elsewhere (like F-droid, or Samsung Store for example) ?

**Comment by redDwarf03** [comment]
i began 6 months ago to work on FDroid
https://gitlab.com/fdroid/rfp/-/issues/2280

i think i forgot one point : [Donated](https://f-droid.org/donate/) to support the maintenance of this app in F-Droid. 😅

**Comment by gdaguin** [comment]
Ok, let's forget the source verification then because there is no way to know if the app comes from F-Droid right now.

**Comment by redDwarf03** [comment]
Ok. No pb
