### ISSUE TITLE
Restoration words

### ISSUE THREAD

**Issue by Raymond91540** [redDwarf03/archethic_mobile_wallet#300]
### Describe the problem you discovered

I downloaded the ARCHETIC wallet application for my Iphone today.
I wanted to create my account and I was offered a list of words to ensure the restoration of my account in case of need.
The list of words proposed was not totally identical to those proposed in the word validation phase.
I did the operation both in French and in English and each time the same type of difference between the words.

### Describe the solution you'd like

I want the proposed words to be the same as those in the validation

**Comment by redDwarf03** [comment]
Hello
Thanks for your feeback.
Could you give me please:
- Version of app (available on about menu)
- If possible, an example with a photo of different screens with the 24 words (while the bug bounty process, seeds are just for testing)

**Comment by Raymond91540** [comment]
You can close that bug.

**Comment by Raymond91540** [comment]
Hello
I downloaded 1.07 version of Archetich Wallet from App Store.
I used Archetic Main Network to follow the process to get a new account.
That morning i tryed to reproduce the issue seen yesterday on seed words.
Today no differencies between words offered and validation of words.
I think have understood the root cause of the problem and this one can comme back.
When you see all words offered, there is no informations that all the list is visible and you have to do a scroll down to see the the whole list.
That why when you are in the validation page, the order of the words is not the same and you can think it is not the same words because such of them were hidden in the previous page.
It is not a bug just a source of problem for those want to create an account.
I think and i hope my experience will be a good feedback for your risk management process.
Have a good day.
Raymond

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by redDwarf03** [comment]
Hello Raymond. Thank you for your feedback. I take in charge your feedback
