### ISSUE TITLE
Error with lira currency

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#349]
### Describe the problem you discovered

use DTO to parse "tli" value to "try" value

**Comment by Chralu** [comment]
We should : 
 - adapt Lira currency name when interacting with CoinGecko
 - when coingecko load fails, Display a loading error message instead of the empty chart
 - display account balance even if coingecko load fails.

**Comment by redDwarf03** [comment]
The currency management will be decommissioned. I close this issue
