### ISSUE TITLE
Specifications of the topic "Interactions/Interoperability with DApps”

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#410]
Explore existing interoperability systems with Dapps
This must be done in the context of multiplatforms
Define a list of solutions

Define where do we want to be positioned

**Comment by redDwarf03** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-wallet/410?planning-poker) with Zenhub @Chralu @Neylix @samuelmanzanera

**Comment by apoorv-2204** [comment]
You might want to take a look at Polkadot, and Cosmos.

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/aeip/blob/main/AEIP-4.md
