### ISSUE TITLE
When an NFT is moved from one category to another, the image of the old moved NFT appears on another NFT

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#480]
### Describe the problem you discovered
If users have few NFT in a same category and they delete one, the image of the old moved NFT appears on another NFT

**Comment by Esquimor** [comment]
After looking for this issue, I think the bug come from:    https://github.com/archethic-foundation/archethic-wallet/blob/90db4a6a6c6f646b818fc7d0c1a387e9e65a633a/lib/ui/views/nft/layouts/components/nft_list_detail_popup.dart#L80     
The user can quit the popup before the code finish to excuted. So, the app generate an error.


So, I think of 3 solutions:

1. RefreshNFTs in an asynchronous function
2. Move to a higher component
3. Add a loader to make await the user.

@redDwarf03 what do you think ? And whitch solution seem the best ?

**Comment by redDwarf03** [comment]
Could you try 1) please

**Comment by Chralu** [comment]
Hi,

Just to share my mind, I would be surprised that the **"image swap issue"** would be related to the error seen when popup is quit early.

I think the issue is a classical lack of `Key` on list children widgets (https://www.youtube.com/watch?v=kn0EOS-ZiIc).

**Comment by Esquimor** [comment]
Hi,

Ok, I may be miss that, I will check.

**Comment by redDwarf03** [comment]
Category no longer exists in V3
