### ISSUE TITLE
Image's size by screen density

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#491]
### Describe the problem you discovered

for the images, it would be maybe interesting to decline them by screen density

### Describe the solution you'd like

Use https://docs.flutter.dev/development/ui/assets-and-images#resolution-aware

**Comment by gdaguin** [comment]
This issue needs to be close, no ?

**Comment by redDwarf03** [comment]
fixed with https://github.com/archethic-foundation/archethic-wallet/pull/743
