### ISSUE TITLE
Delete https://github.com/UNIRIS/archethic_mobile_wallet

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#52]
### Solution

@seb-uniris , is it possible to delete the archethic_mobile_wallet from Uniris repo please
Thx

**Comment by internet-zero** [comment]
@redDwarf03 , 
Yes, sure, 

Give us sometime to discuss and we will close it

**Comment by ghost** [comment]
It's a fork so yes we can remove it

**Comment by ghost** [comment]
Repo have been deleted
