### ISSUE TITLE
Hide account

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#525]
### Is your feature request related to a problem?
Users should want to hide some accounts if they have too many accounts/services to manage in the keychain.
It's possible too, they don't want manage some accounts/services in the wallet directly because they depend directly from a dapps.

### Describe the solution you'd like
Add a feature to hide accounts
These settings should be on-chain because if users delete from one device or use the wallet in another device, they should want to recover the settings without redoing everything.

### Additional context
Need a AEIP to store wallet's settings

**Comment by Esquimor** [comment]
What is the difference with: https://github.com/archethic-foundation/archethic-wallet/issues/551 ?
