### ISSUE TITLE
Language choice

### ISSUE THREAD

**Issue by n0uki63** [redDwarf03/archethic_mobile_wallet#554]
### Additional context

Have the possibility to select the language on the first screen, before creating or importing the wallet

**Comment by Esquimor** [comment]
I will try to do it.

**Comment by redDwarf03** [comment]
please @Esquimor, add the field in the welcome page with a link for example "change the language" and the link opens a modal window with the choice of the language
thx

**Comment by Esquimor** [comment]
Maybe close this issue.
