### ISSUE TITLE
Change address and public key in uppercase

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#559]
### Is your feature request related to a problem?
In the application, the address or the public key are sometimes in uppercase, sometimes in lowercase.

### Describe the solution you'd like
Uniformise display with uppercase

**Comment by Esquimor** [comment]
I tried to list all the locations where the address or public key is located:

**Address**

- Address Book > In a Contact > Copy a Address
- Main Page > Recent transaction
- Main Page > Detail for recent transaction
- NFT > Copy QrCode of a NFT

**Public Key**

- Address Book > In a contact > Copy a Public key

I don't find in others places in the application.

Also, do I have to only Uppercase when an address or public key is show or also when it is written (ex: in a form) ?

**Comment by redDwarf03** [comment]
twice please
