### ISSUE TITLE
check if internet is OK

### ISSUE THREAD

**Issue by n0uki63** [redDwarf03/archethic_mobile_wallet#593]
### Is your feature request related to a problem?

If the app is running without internet connexion, so U can have some wrong message.

Exemple : if u try to restore the wallet, after write the seed, on validation, you receive a message like "no wallet for this seed".

### Describe the solution you'd like

Add a red banner at the top of screen for indicate "no internet connectivity".

Or add a check of connectivity before action and send an appropriate message.

**Comment by redDwarf03** [comment]
- [x] : create notifier with connectivity_plus lib
- [x] : inform user in top bar is the app is not connected
- [ ] : test

For the moment, connectivity_plus is not fiable. find another lib or way to check connectivity.
