### ISSUE TITLE
Optional display optimization suggestion 

### ISSUE THREAD

**Issue by SUBLIMENUIT13** [redDwarf03/archethic_mobile_wallet#625]
### Is your feature request related to a problem?

When sending a created token, at the time of sending, before validate with PIN, we have [The total amount] Space [Token name]. In the case of à hight amount or / and a token with a long name, the display is poorly optimiser because the name will go to the line in a "anarchic" way

### Describe the solution you'd like

You should put the amount on the top line and the name of the token below in order to have example:
10000000000 RED 
TOKEN

But like this:

1000000000 
 RED TOKEN.

Nothing important its just détails. Thx

**Comment by redDwarf03** [comment]
Hello thank you for your issue. i tried but i haven't the issue
Could you give me your device model or resolution please 

<img width="362" alt="Capture d’écran 2023-01-17 à 23 22 30" src="https://user-images.githubusercontent.com/68340133/213025384-4439a784-c27b-4f7d-8a07-30383b6f8b30.png">

**Comment by SUBLIMENUIT13** [comment]
![20230118_163233](https://user-images.githubusercontent.com/122875578/213214898-36066973-27e3-4b16-9bf7-818bc8d54621.jpg)
Sorry for the picture. Iam on the phone. But its not when you created the token its when you send it. 
Example i creat a token for a private access like 
"🌙SUBLIME🌙" and i want to send for exemple 1million or more, we have the name token on 2 lines like my picture. Here its the 2d moon but, can be a letter. 
So maybe a line for the amount and à 2nd line below for the symbol. 
I repeat its very small detail. Not important. A simple display optimisation. 
This happen on my 2 phones: Redmi 9C / Galaxy  A04s.

**Comment by SUBLIMENUIT13** [comment]
![20230118_164918](https://user-images.githubusercontent.com/122875578/213220780-4df6394f-1f1b-494f-974c-f28f4ec03a40.jpg)
Moreover if the token name is long, the display in the transaction history does not seem appropriate. Perhaps it is also necessary here to store this by line or other solution? Idk.

**Comment by redDwarf03** [comment]
![Capture d’écran 2023-12-01 à 17 45 01](https://github.com/archethic-foundation/archethic-wallet/assets/68340133/e8f5e74a-82de-4d18-ac46-db54fe6fc348)
![Capture d’écran 2023-12-01 à 17 45 12](https://github.com/archethic-foundation/archethic-wallet/assets/68340133/ed4a3257-9d4d-4f60-8482-72cff31e78aa)
