### ISSUE TITLE
Add explanation to add a translation in Contributing Guide

### ISSUE THREAD

**Issue by Esquimor** [redDwarf03/archethic_mobile_wallet#631]
### Is your feature request related to a problem?

Describe the way to add a translation for new developer.

### Describe the solution you'd like

In the "CONTRIBUTING.md" add a section with the explanation for add a translation.

### Additional context

As a new developer, I struggle to find the right way to add a transaltion.

**Comment by redDwarf03** [comment]
Hello. Good idea to help contributions. thx
