### ISSUE TITLE
Loss of thousand format

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#662]
### Describe the problem you discovered

When we create a token with a supply >= 1 000, if we click on cancel in the confirmation page, the thousand formatter loses the format

**Comment by NirbhaySirsikar** [comment]
I am not able to recreate the issue,
I tried to create a token of 1 010 and after clicking on cancel on confirmation page I see 1010.0 in input field.
Is this what you were talking about or is the bug already fixed?
Screenshots would be helpful :)

**Comment by redDwarf03** [comment]
Hello. Sorry for the delay for my answer.
Normally this issue is always open. I will try to add examples.
