### ISSUE TITLE
Change the position of the add token button

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#663]
### Describe the problem you discovered

When a user has too many tokens in the main screen, token tab, the "add token" button is on the bottom of the page.
Find a way to have a better user experience

**Comment by Esquimor** [comment]
My proposal, only show the first 3 token and add a button to see all the token (show more).

Below, the "show more", we can keep the button to add token.

What do you think ?

**Comment by redDwarf03** [comment]
I would like to give to user more feature around token search but the back office blockchain side is not ready. 
For the moment, i would like to let the complete list.
You can perhaps 
- remove the actual button "create a token"
- add an (+) icon button just on the right of the "token" tab title text instead
