### ISSUE TITLE
Message icon too small in recent tx

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#664]
### Is your feature request related to a problem?

With a small screen, the icon to display message in recent tx list is difficult to use.
Find a better way to access quickly to message

**Comment by Esquimor** [comment]
Do you speak about the arrows in recent transaction or do you speack in icon when we open a transaction ?

**Comment by redDwarf03** [comment]
The bubble icon to display message joined in a transaction

**Comment by redDwarf03** [comment]
This issue concerns this: 
![100EF3A0-B2DD-4532-A1AF-DC16B1CDBA3D](https://user-images.githubusercontent.com/68340133/218329727-bf5be4ec-ab5f-4a13-a256-f991c0e6673b.jpeg)

**Comment by Esquimor** [comment]
My proposal:

![Sans titre](https://user-images.githubusercontent.com/32507951/219899116-aae1facd-eefd-4fae-a2a7-f2fc8dfd2797.png)



Tell me if you like it. @redDwarf03 

Sorry for the quality of the image, I can't find a way to disable to screenshot my phone.

**Comment by redDwarf03** [comment]
perhaps something like that. Remove "Consulter le message" and put the icon in the bottom right with a higher size

![Capture d’écran 2023-02-19 à 12 04 41](https://user-images.githubusercontent.com/68340133/219944242-69e24ad1-435c-4032-b15a-81b616669333.png)
