### ISSUE TITLE
NFT - RenderFlex overflowed

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#665]
### Describe the problem you discovered

An error occurs when we add a photo in NFT in a small screen (google pixel 4 for example)

```

════════ Exception caught by rendering library ═════════════════════════════════
A RenderFlex overflowed by 101 pixels on the bottom.
The relevant error-causing widget was
Column
lib/…/components/nft_creation_process_import_tab.dart:34
════════════════════════════════════════════════════════════════════════════════
```

**Comment by NirbhaySirsikar** [comment]
Hi, I am actually new to open source contribution. Can I know how can I run the specific dart file with the resources( like you mentioned about adding an NFT) for debugging purpose. I tried replacing the void main() to: 
void main(){
  runApp(NFTCreationProcessImportTab());
}
But it gives me error: " Bad state: No ProviderScope found".

I guess its not the correct way to do it, so please can someone help me with this problem.

EDIT: 
I tried the following:
runApp(
    ProviderScope(
      observers: [
        ProvidersLogger(),
      ],
      child: const NFTCreationProcessImportTab(),
    ),
  );
But now the app is stuck on the splash screen.

**Comment by redDwarf03** [comment]
Hello. thank you for your contribution :)
i don't recommend to change main method.
You have just to run app with an android simulator (with small screen) and you follow steps to create a new wallet in testnet network. After that, you get some UCOs with the faucet ``https://testnet.archethic.net/faucet``. With the UCOs obtained, you can go in NFT menu and create an NFT to see the error in the log

**Comment by redDwarf03** [comment]
Good first contribution ! thank you
