### ISSUE TITLE
Improve the search in Transaction

### ISSUE THREAD

**Issue by Esquimor** [redDwarf03/archethic_mobile_wallet#678]
### Is your feature request related to a problem?

It is hard to find a transaction and to see all transactions

### Describe the solution you'd like

Somethings like that:

![transactions](https://user-images.githubusercontent.com/32507951/219942589-ca98a2e8-89ba-456a-956f-2a81bead6c59.png)

**Comment by redDwarf03** [comment]
Hello,

There has been a long discussion within the community regarding the number of transactions to display. 10 is considered a good compromise, as 3 is too short for users.

The "All transactions" feature will be available on the Archethic Explorer, and we are planning to improve its UX/UI. After that, we will add a button in the wallet to open the Explorer view with a search feature.

**Comment by redDwarf03** [comment]
V3 include a new tab with 10 last transactions. 
A "All transactions" button will be available to go to the Archethic Explorer via this issue
