### ISSUE TITLE
Format branch and commit with husky

### ISSUE THREAD

**Issue by Esquimor** [redDwarf03/archethic_mobile_wallet#682]
### Is your feature request related to a problem?

I want a clear format for branch and commit

### Describe the solution you'd like

Use [husky](https://pub.dev/packages/husky)

See in CONTRIBUTING.md, who is formatted branch and commit. And enforce it with husky.

**Comment by redDwarf03** [comment]
Good proposal. We will integrate it in some time

**Comment by redDwarf03** [comment]
we are using https://www.conventionalcommits.org/en/v1.0.0/
