### ISSUE TITLE
NFT - Add IPFS, Http and AEWEB url

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#683]
### Is your feature request related to a problem?

For NFTs, the content of a transaction is formatted in a specific way.
In the structure, there is a "content" tag which contains the content (image, PDF, ...) of the NFT. 
In the wallet, only the raw content is managed, i.e. the content of the file converted to base 64, but the NFT structure also allows to store either a url pointing to AEWEB, IPFS or HTTP.

### Describe the solution you'd like

The evolution concerns the support of these URLs

### Example

Example of the "content" tag: 
```
 "content": {
                "raw": "BASE64",
                "ipfs_url": "ipfs://zahygduayzfud",
                "http_url": "https://ssssdssds.com/lispum.png",
                "aeweb": "jhzavfkuz4645654fzef/asset/image.png?strict=true"
            },
``` 

Note that the content type is exclusive. Only one per NFT is possible.

### UI Changes
1. In NFT "Import" tab, remove lines "File", "Photo" and "Take a photo" and replace them with Cards (like NFT categories' cards)
2. Add 3 new cards: 

- IPFS url
- AEWeb url
- web url  

Try to find a good background UI for each card

3. For these 3 new cards, if user clicks, a new Sheet opens (like ``AddAccountSheet`` widget)
4. User can fill a url (required field, check the structure of url). Add a paste icon in the right of the field
5. When the user validates, the sheet closes and the preview is displayed (like actually with photo/file)

### Backend
- Add new type in ``FileImportType``
- Add ``fileUrl`` in ``NftCreationFormState``
- Manage the addition of url in ``NftCreationFormNotifier``
- Take in charge the preview of file with url
- Take in charge the loading of file with url

### Additional context

- Warning, due flutter web, an update of pickfile management is available in https://github.com/archethic-foundation/archethic-wallet/pull/681

- This issue will be useful to develop NFT Collection management in the wallet. It could be interesting to create a widget to manage the content of the NFT whether it is unique or in a collection (photo, url, file, ...)

**Comment by Esquimor** [comment]
Hello, after some test, for ipfs, I need to change the url requirement.

So the url will look like this:
ipfs://QmUyARmq5RUJk5zt7KUeaMLYB8SQbKHp3Gdqy5WSxRtPNa/SeaofRoses.jpg

Are you agree @redDwarf03 ?

**Comment by redDwarf03** [comment]
Please refer to https://docs.ipfs.tech/how-to/address-ipfs-on-web/

**Comment by redDwarf03** [comment]
This issue is not completed. Some errors to fix

**Comment by redDwarf03** [comment]
Tests ok. All fix are commited in https://github.com/archethic-foundation/archethic-wallet/pull/721
