### ISSUE TITLE
[Feature] - Rename a contact

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#70]
### Solution

add in contact's detail screen, a feature to rename the contact

**Comment by Esquimor** [comment]
Hi,

I have found your project and I find it interesting.
I am a developer in React/Node and I want to help you with this wallet.

So, can yo describe a little more this feature ?

- I can add a button to make the field editable
- I can make it editable by clicking on the name
- Or other

Can you just tell me which way to go?

@redDwarf03

**Comment by redDwarf03** [comment]
Hello @Esquimor . Thanks for you message. Do you want to contribute with flutter? 
for this (old) issue, I think we can change the name directly in the detail page of the contact with an editable input text. We cannot change contact with account type
We can discuss about this on discord or telegram if you want

**Comment by Esquimor** [comment]
Hello @redDwarf03 , yes, I want to help.
But I am new with flutter. So I go for "good first issue" for now.
Ok for discord.

**Comment by redDwarf03** [comment]
contact me here: https://discord.gg/HguTESdA
