### ISSUE TITLE
Problem with creating a new wallet

### ISSUE THREAD

**Issue by margarita-uniris** [redDwarf03/archethic_mobile_wallet#719]
### Describe the problem you discovered

When I create a new wallet on the mainnet network, I create a new secret phrase, and after I need to create Security access with Password, PIN, Yubicloud OTP, Face ID or Touch ID.  So, Here is the problem: after the creating the security access, there is a processing part, which finish by error. I tried all security access, the same result. 
I met already this issue in February.

### Describe the solution you'd like

Be able to create a new wallet on the mainnet network

**Comment by redDwarf03** [comment]
Consensus error blockchain side. Fix in progress

**Comment by Stef369** [comment]
The problem still exists, I can't go through the whole process.
Is there or will there be a communication about that on Discord ?

**Comment by redDwarf03** [comment]
Hello @Stef369, what is the error message please ?

**Comment by Stef369** [comment]
Hello, Ive tried again thi morning and that's all good, thanks

**Comment by Stef369** [comment]
Hello, I've transferred 92 UCO (8$ nearly) from BSC to Archetic Mainnet.
The message of transfer was that everything is OK, and i don't see the 92 UCO on the BSC in my metamask, but I don't see them either on my archetic wallet...
Is there something else I need to do ?

**Comment by redDwarf03** [comment]
@Stef369 Can you give me the list of contract's addresses displayed on the bridge's app please ?

**Comment by Stef369** [comment]
My BSC address is : 0x6193a1C8fdD284A6B3395BCcB519e75FC6B7Bb09

My Archetic account adress is : 0000c6d92eda359ac4a56533f459ef5edf2d7b58279a7e5ffd1da87d22658614de74

Last transaction is : 0x6ff9e3b4925458c99d39b365c51ccec10710c7625a93e4f5baa614a4dfb9b412

Do you have all you need ?

**Comment by redDwarf03** [comment]
you received 92 UCO in your archethic's address. https://mainnet.archethic.net/explorer/transaction/0000c6d92eda359ac4a56533f459ef5edf2d7b58279a7e5ffd1da87d22658614de74
You don't see in your wallet app the transactions ? Are you sure 0000c6d92eda359ac4a56533f459ef5edf2d7b58279a7e5ffd1da87d22658614de74 is your address in the wallet ?

**Comment by Stef369** [comment]
I really looks like so : 
![image](https://user-images.githubusercontent.com/118367083/228896045-6d6fb07c-b6d1-45f6-92c5-41be07f66616.png)

![image](https://user-images.githubusercontent.com/118367083/228896193-e1bf82a8-41f0-41ef-b40f-0505733ae2fc.png)

**Comment by redDwarf03** [comment]
could you show me your menu (click on burger menu) ?

**Comment by Stef369** [comment]
What's burger menu ?
This ?
![image](https://user-images.githubusercontent.com/118367083/228899093-ef0d2012-3a93-4c98-b478-6b791bc970f7.png)

**Comment by redDwarf03** [comment]
yes. thank you. could you go to "Sécurité" -> "Resynchroniser le wallet" please

**Comment by Stef369** [comment]
It worked, thanks a lot !

**Comment by Stef369** [comment]
Actually, quick feedback, it would be great to have a little "refresh" button on the main screen showing the tokens and amounts.
Thanks again.

**Comment by redDwarf03** [comment]
@Stef369 , thank you for your feedback. I will think about your proposal and add in the backlog. Don't hesitate to send proposals and share to the community your ideas in telegram or discord channels 👍🏻

Just one thing. You can with windows use pull to refresh action to refresh datas

**Comment by Stef369** [comment]
Hi, ok, I hadn't think about that.
So are you the PO on the archetic Wallet ? Are you located in France ?
Actually I am a scrum master and agile coach. I am looking forward new challenges, in particular in the blockhain domain. Are by any chance looking for a scrum master ?

**Comment by redDwarf03** [comment]
Yes, i'm the french PO
No sorry, we are not looking for a scrum master
