### ISSUE TITLE
Add a confirmation popup when users leave NFT creation process

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#730]

**Comment by Esquimor** [comment]
Hi @redDwarf03 ,

I think to use this sentences:

En:

Title: Are you sure you quit creating nft?
Subtitle: All progress will be lost.
Leave: Leave
Continue: Continue

Fr: 

Title: Etes vous sur de quitter la création de NFT ?
SubTitle: Toute progression sera perdu
Leave: Quitter
Continue: Continuer

What do you think about ?

![image](https://github.com/archethic-foundation/archethic-wallet/assets/32507951/32b302fe-05c3-4294-a198-4570bf409b08)

**Comment by redDwarf03** [comment]
Title: Confirmation de sortie du processus de création d'un NFT
Subtitle: Êtes-vous sûr de vouloir quitter le processus de création du NFT ? Toutes les informations que vous avez saisies jusqu'à présent seront perdues. 
Left button: Non
Right button: Oui

Title: Exit NFT Creation Process - Confirmation
Subtitle: Are you sure you want to exit the NFT creation process? All the information you have entered so far will be lost.
Left button: No
Right button: Yes
