### ISSUE TITLE
Multi-recipients doesn't work in recent transactions list

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#745]
### Describe the problem you discovered

If a transfer transaction has many recipients, only the last one appears on the recent tx list

### Describe the solution you'd like

Separate in many lines the transaction (one line per recipient)

**Comment by Esquimor** [comment]
How it is possible to have a transaction with many recipients ?
So, I can have an example to manage the ticket.

Thank's you.

**Comment by redDwarf03** [comment]
For example, you can create a wallet on the testnet, get some UCOs from the Faucet
After that, you create a website with AEWeb from your wallet's account.
When you create a website on AEWeb, the wallet account sends UCOs to fill 2 new chains (the reference chain and the file chain).
Explanation: https://wiki.archethic.net/participate/aeweb/how-it-works

Example. See the ledger / UCO info in this tx: https://testnet.archethic.net/explorer/transaction/00007AC7AD359C5D2727B53236F06F1E7ADC2FA61EE4CDF125ECC0CAC6BC898102FD 
Normally, we should see these 2 tx in the wallet but no
