### ISSUE TITLE
Cannot build aewallet

### ISSUE THREAD

**Issue by vonclutch** [redDwarf03/archethic_mobile_wallet#874]
### Describe the problem you discovered

Hey guys, 

i can't build AEWallet, its give me dependencies errors.

> Resolving dependencies...
> Note: file is pinned to version 7.0.0 by integration_test from the flutter SDK.
> See https://dart.dev/go/sdk-version-pinning for details.
> 
> 
> Because patrol <3.0.0 depends on integration_test from sdk which depends on file 7.0.0, patrol <3.0.0 requires file 7.0.0.
> And because xdg_directories >=0.2.0 <1.0.1 depends on process ^4.0.0 which depends on file ^6.0.0, patrol <3.0.0 is incompatible with xdg_directories >=0.2.0 <1.0.1.
> And because flutter_local_notifications >=9.6.0 <10.0.0-dev.1 depends on flutter_local_notifications_linux ^0.5.0+1 which depends on xdg_directories ^0.2.0+1, patrol <3.0.0 is incompatible with flutter_local_notifications >=9.6.0 <10.0.0-dev.1.
> So, because aewallet depends on both flutter_local_notifications ^9.7.1 and patrol ^2.2.3, version solving failed.
> 
> 
> You can try one of the following suggestions to make the pubspec resolve:
> * Try upgrading your constraint on patrol: flutter pub add dev:patrol:^3.1.0
> * Try upgrading your constraint on flutter_local_notifications: flutter pub add flutter_local_notifications:^16.2.0
> 

If i update flutter_local_notifications to the last version, the project kind of build but there are deprecated functions and you need to change some files:

Some functions are grouped now and some refractoring is probably needed in NotificationsUtil.dart. 

informations: Flutter (Channel beta, 3.17.0-1.0.pre.3, on Manjaro Linux 6.6.3-1-MANJARO,  locale en_US.UTF-8)

### Describe the solution you'd like

Should just run `flutter pub get` && `flutter run`  for it to wroks.

**Comment by redDwarf03** [comment]
Thank you for your feedbacks
We maintain the app with flutter 3.13.x and dart 3.1.x for the moment
We will upgrade flutter version and dependencies soon with stable version only
