### ISSUE TITLE
UI/UX Feedbacks from Community (_ on TG FR)

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#876]
### Describe the solution you'd like

From _ from TG FR 2023/12/08

- [x] Dans un premier temps le bouton « i » à côté de l’année dans le graphique affiche une popup avec l’ancienne charte, ces anciennes modales sont un peu présentes de partout.
Les modales dont je te parle valent aussi pour celles dans les paramètres 

- [x] Dans le choix de la devise, BTC à un problème d’alignement avec les drapeaux

- [x] J’ai l’impression que la police d’écriture n’est pas mise à jour sur le wallet.
Vous avez dit avoir changé la police lors de la mise en place du nouveau site mais je crois que c’est encore celle de l’ancienne charte graphique.

- [x] Il y a un problème de marge sur la page d’accueil, je m’explique, tous les composants devraient avoir exactement la même marge pour ne pas que ça paraisse déséquilibré, je te propose de baser ta marge sur le bouton paramètres et sur celui des notifications, pour que tout ce qui soit en dessous ai la même marge.

- [x] La couleur du gris dans le blog est un peu spéciale, elle dénote avec le reste qui est bien dans la charte

- [x] Je trouve justement, que la partie grise du blog est super grande compte tenue des informations affichées dessus, d’autre part, je ne sais pas si c’est propre à mon device (iPhone 14 Pro Max) mais l’article « Archethic Rebirth » à le « The » de « The Ecosystem Awakening » au milieu de rien, je te ferai un screen si tu ne vois pas de quoi je te parle.

- [x] N’hésite pas à bien marger le 1er article de blog sur la gauche.

- [x] Lorsque l’on quitte l’app et qu’on la récup dans le multitâche par exemple, le nouveau visuel pour cacher les infos de l’app est sublime mais j’ai des bordures noires en haut et en bas, encore une fois peut-être dues à mon device.

- [x] La barre de recherche des NFTs y’a quelques soucis, premièrement, lorsqu’on clique dessus, ce qui est marqué ne disparait pas ou ne s’éclaircie pas, niveau UX, ce n’est pas top, deuxièmement, il faudrait plutôt mettre une loupe à côté du bouton « coller » plutôt que le bouton « search » qui est bizarrement mis d’un point de vue UX.

- [x] De manière générale, mettre les input de recherche à gauche au lieu de les centrer, ça fait bizarre.

- [x] Les boutons, les « calls to action » c’est l’un des points les plus importants, visuellement parlant et au niveau de l’expérience utilisateur.
Dans un 1er temps, le dégradé, outre le fait que ça fasse projet des années 2015, ça perturbe la bonne visibilité de l’information du bouton, dans un 2nd, il faut SURTOUT, que tu les agrandisses sur le haut, qu’ils fassent toute la largeur c’est super mais double les vraiment ou du moins fais un x1,5/1,8 sur la hauteur, ça permettra 2 choses, augmenter la taille de la police et augmenter les infos que tu peux y afficher, enfin n’hésite surtout pas à mettre le titre de ces boutons en gras pour que ça ressorte.
Ce sont des boutons un peu comme ça qu’il faudrait
![IMAGE 2023-12-08 15:35:44](https://github.com/archethic-foundation/archethic-wallet/assets/68340133/7adc493f-e2c4-4fb6-8e6a-cc06b59b895a)
J’ai l’impression, que les titres dans les boutons ne sont pas centrés verticalement, ils semblent un peu en hauteur par rapport à la ligne médiane horizontale.

- [ ] Pour les boutons qui sont collés en bas, style ceux de « Address Book » et « Keychain », je te propose un padding bottom, ils font un peu affalés sur le bas

- [x] Dans les paramètres, la couleur de fond adaptée serait celle utilisée sur le bandeau d’un token créé dans l’accueil et pareil le gris du haut fait bizarre.

- [ ] Les icônes dans les paramètres devraient avoir un padding car elles sont trop collées au bord ça ne fait pas beau.

- [ ] À mon sens, le placement de la version n’est pas bon, il faudrait le mettre en dessous des boutons ou tout en haut (à droite à mon sens).

- [ ] Dans le signin, le choix du Network devrait être centré.

- [x] Le premier bouton affiche « ok », je pense que « continuer » serait plus adapté.
Je reviens sur le naming des boutons, il faudrait qu’ils soient ISO, donc qu’ils aient tous le même format, donc avec une majuscule et sans icône comme ça peut être le cas lorsque l’on veut ajouter quelque chose, il y a un « + », à mon sens, le mot « Ajouter » suffit (je parle dans l’app pas sur la signin).

- [ ] Lorsqu’on valide le nom du Wallet, pareil, problème de marges, il faudrait mettre exactement les mêmes que sur l’app, là ce n’est pas aligné et le texte est trop étiré donc trop proche de la scrollbar.

- [x] Pour la seed, faire un design plus dans le thème de l’app (peut-être reprendre celui des transactions, les bords blancs et le fond gros perturbent un peu l’homogénéité de l’app.

- [x] Toutes les vues d’après dans le process de signin, toujours les marges.

- [x] L’ombrage général des boutons est également trop important en bas, il devrait un peu plus être centré et moins noirci

- [x] La page d’accueil lorsque l’on est pas co est sublime, l’ADN est magnifique, les textes en blanc ressortent très bien.
Je pense qu’il faudrait vraiment se baser sur ce design et beaucoup jouer sur le blur lié à l’ADN (très en tendance de design pour 2024 le blur)

- [ ] Dans la page d’accueil une fois connectés, lorsque l’on a pas rentré la seed phrase, le message en bas dans le rectangle noir serait plus beau dans le design de « Aucune transaction pour le moment », encore une fois, ça dénote trop.

- [x] J’ai oublié le hover des boutons en blur/transparence qui n’est pas de la même taille pour toutes les icônes, ça touche toute l’app

Pour résumer, je pense qu’un très gros travail de repasse sur les marges globales de l’app pour qu’elles soient homogènes, un bon travail sur les boutons et onglets de recherche et un bon travail sur le design global des modales qu’il faudrait je pense mettre sous forme de « blur » rendraient déjà beaucoup plus pro

**Comment by redDwarf03** [comment]
@gdaguin si tu t'ennuies lol

**Comment by quentin-legraverend** [comment]
I don't want to open a dedicated issue so I put this here:
- On macOS, the logo should be reworked. I don't know if it's the same everywhere (Windows, Linux) but this logo is not good-looking in macOS env (square with no border radius).
- Also, most macOS application logos are mostly 2D logos with shadow effects. In that sense Archethic logo which has a kind of "3D" effects looks mismatched.

I really think those kind of details can afraid people during hard launch. People might think: "The project team can't even make a smooth looking logo so why should I believe in this project?"

There are so many projects out there with nearly perfect and super smooth UI/UX. AE really needs to be one of those.

![image](https://github.com/archethic-foundation/archethic-wallet/assets/6078020/dabfa000-ddf2-4562-a53d-a6b888058757)
