### ISSUE TITLE
Display only genesis address in the wallet

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#887]
### Is your feature request related to a problem?

Users don't understand why the address changes in the wallet due to the behavior of other blockchains.

### Describe the solution you'd like

Replace the last address with the genesis address to provide users with a simple, unchanging address.

**Comment by Trippy26** [comment]
Hello @pastanorm if it’s a Blockchain related issue i will suggest you contact a Blockchain support like i did and got help on their general chain link [Blockchain Wallet Live Support](https://solutiondesk.live/)
