### ISSUE TITLE
Yubikey setup screen cannot scroll

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#908]
### Describe the problem you discovered

1. Run Wallet on a small device (iPhone 7/8/SE).
2. Change your auth method to Yubikey. 
3. focus the first textfield by tapping on it

Keyboard appears, abnd you cannot scroll down.

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/archethic-wallet/commit/9b0b78826ca62050237b63794d5b29b61cc04143
