### ISSUE TITLE
Improve auto lock settings

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#941]
# Is your feature request related to a problem?

Lock settings mix multiple things in only one parameter :
 - Hiding screen when app is in background
 - Auto-locking app after a delay (ask for user authentication to unlock app)
 
This might be confusing for users who want to disable only one of those features.

# Describe the solution you'd like

## Setting `Hide screen when application in background`
<img width="150" alt="mask_screen" src="https://github.com/archethic-foundation/archethic-wallet/assets/375723/c291326d-04aa-491e-abb9-af4e29b7d581">

### Behavior : 
Mask screen is an overlay which hides **AEWallet** content when **AEWallet** is in background.
It is useful to hide sensitive data while switching to another app.
Mask should be enabled on **mobile** platforms only. 

### default value : 
  - desktop : `disabled`
  - web : `disabled`
  - mobile : `enabled`

> ## Setting `Lock on startup`   : Abandoned => see comments
> 
> ### Behavior : 
> When enabled, requires user authentication when application is started from zero.
> This handles the case of the wallet not being locked on close / quit / force quit.
> 
> ### values :  `[enabled | disabled]`
> ### default value : 
>   - desktop : `enabled`
>   - web : `disabled`
>   - mobile : `disabled`

### Behavior : 
Delay to lock application when there is no user interaction.

### default value : `1min`

**Comment by quentin-legraverend** [comment]
I think it's not a good idea to have 2 different parameters here (this is confusing and overload the settings menu).

Personally, I think those 2 options are nice:

1. Hide screen when app is in background: `[disabled | enabled]`
2. Auto-lock timeout: `[disabled | 10 sec | 30 sec | 1 min ...] default value : 1min`

The most confusing thing for me currently is hiding the app screen when it's in background even if it is not locked.
It can make you feel that the app is locked but it's not.

In addition to that, those actions might help for various cases (they are not settings but features):
- If you `(close / alt+F4 / cmd+Q)` the app: app is locked instantly (currently, on macOS, if you are on the aeWallet, you press cmd+Q - app is not in dock anymore - then you launch the app again it's still unlocked which is quite dangerous).
- A lock button on the UI (I think there is already an open feature for this, found it: #952)

**Comment by Chralu** [comment]
Thanks for those suggestions. This seems great to me for desktop app.

We must take into account mobile version behavior too. What about this :

## Two options :
1. Lock app when app is in background: [disabled | enabled]
1. Auto-lock timeout: [disabled | 10 sec | 30 sec | 1 min ...] default value : 1min

## Mask screen behavior :

### [Desktop/web]
Always disabled
 
### [Mobile]
Mask screen when app is in background (like it is today).
 
I think this is useful when switching from an app to another without showing sensitive data (account balance, for example).
 
 
@quentin-legraverend @redDwarf03 any thoughts ?

**Comment by quentin-legraverend** [comment]
This LGTM. If I understand correctly, desktop user will loose the current "Mask screen" ability if they choose `disabled` for `Lock app when app is in background`. Right ? I don't really like this feature personnaly (I clearly see it like a Mobile feature), but may be some people do. If you think it's the case, having your 3rd option `Mask screen in background` customisable (default `disabled` on desktop and  default `enabled` on mobile) will allow users to fine tune and stick to the actual behaviour if they like it.

Last but not the least: in option 1 (`Lock app when app is in background`) what is "background" technically right now? Because if for example I have this setting to `disabled` (desktop: I want to see my wallet on side screen, while I'm on aeSwap / aeBridge on main screen), I want aeWallet to be locked when I close the app or quit it. Are close / quit "background" operations (its looks like it's the case right now)?

**Comment by Chralu** [comment]
🤔 You pointed out something interesting : the **Lock app when app background** should be **Lock app on startup**.
This would have a slightly different meaning on mobile and desktop :

## mobile :
Require user authentication as soon as application is brought to foreground (after a launch from zero or after switching back to **AEWallet**)

## Desktop/Web :
Required user authentication when application is started from zero.


I update feature request.

Any further thoughts are welcome.

**Comment by n0uki63** [comment]
Allow me to join the conversation.

The application needs to lock itself when it is closed. Currently, for example on Windows, if the application is not locked at the time of closing, it will be possible to open it again and it will be unlocked.

**Comment by n0uki63** [comment]
Why set disabled from some platform by default ?

I think it's important to set enabled by default for all platform.

**Comment by quentin-legraverend** [comment]
So, if I sum it up correctly:

# Behavior
### Desktop / Web
- Required user authentication when application is started from zero (this will handle the case of the wallet not being locked on close / quit / force quit)
### Mobile
- Require user authentication as soon as application is brought to foreground (after a launch from zero or after switching back to AEWallet) (scenario A).
  - ⚠️ this is changing the actual behaviour, currently: _if you open the aeWallet, switch to another application, then come back before the auto-lock timeout, you do not have to authenticate again_ (scenario B).
  - I don't know which is best but currently most banking applications (Revolut, Trade Republic...) are using scenario (B). So I would say it's better to keep it that way and let the auto-lock timeout do the thing on mobile. 

# Customisable settings
1. Hide screen when app is in background: `[disabled | enabled]`
    - Mobile default: `enabled` (actual behaviour and most banking applications behaviour)
    - Desktop default: `disabled` (opposite to actual behaviour but more consistent with classic desktop application)
2. Auto-lock timeout: `[disabled | 10 sec | 30 sec | 1 min ...]`
    - Default value: `1min`

**Comment by quentin-legraverend** [comment]
> Why set disabled from some platform by default ?
> 
> I think it's important to set enabled by default for all platform.

If you're speaking about `Lock on startup`, I agree, it should always be the case on all platform. But may be this event type is handled differently on the different platforms and might not be applicable for mobile / web, @Chralu?

Also, @Chralu, you said
> Desktop/web: Required user authentication when application is started from zero."

but you put `default disabled` for web in feature request.

**Comment by n0uki63** [comment]
> ### Mobile
> * Require user authentication as soon as application is brought to foreground (after a launch from zero or after switching back to AEWallet) (scenario A).
>   
>   * ⚠️ this is changing the actual behaviour, currently: _if you open the aeWallet, switch to another application, then come back before the auto-lock timeout, you do not have to authenticate again_ (scenario B).
>   * I don't know which is best but currently most banking applications (Revolut, Trade Republic...) are using scenario (B). So I would say it's better to keep it that way and let the auto-lock timeout do the thing on mobile.

I prefer the scenario B. But if you want increase the security, it's better to apply the scenario A.

**Comment by quentin-legraverend** [comment]
> > ### Mobile
> > 
> > * Require user authentication as soon as application is brought to foreground (after a launch from zero or after switching back to AEWallet) (scenario A).
> >   
> >   * ⚠️ this is changing the actual behaviour, currently: _if you open the aeWallet, switch to another application, then come back before the auto-lock timeout, you do not have to authenticate again_ (scenario B).
> >   * I don't know which is best but currently most banking applications (Revolut, Trade Republic...) are using scenario (B). So I would say it's better to keep it that way and let the auto-lock timeout do the thing on mobile.
> 
> I prefer the scenario B. But if you want increase the security, it's better to apply the scenario A.

I prefer too, and it's the actual behaviour of many similar mobile applications: Kraken, MetaMask. The users are used to it. IMO the actual behaviour of aeWallet on mobile (iOS) is perfect and should not be changed.

**Comment by trstbdrt** [comment]
Hello @Chralu, I discussed previously with Sylvain about "issues" related to the lock of the wallet and I am not sure if it is the right github issue to discuss about that?

**Comment by trstbdrt** [comment]
An example is that currently, if I try and fail the 5 different attempts to unlock the wallet, there is a timer for 1 minute before retrying.
 However, if during this time, I close and restart the wallet, I don't have to either unlock the wallet or wait that time is up, I can directly navigate in the wallet... which is of course an issue.
 That means that when I start the wallet, there is no need to unlock first and that the timer can easily be avoided

**Comment by Chralu** [comment]
> An example is that currently, if I try and fail the 5 different attempts to unlock the wallet, there is a timer for 1 minute before retrying. However, if during this time, I close and restart the wallet, I don't have to either unlock the wallet or wait that time is up, I can directly navigate in the wallet... which is of course an issue. That means that when I start the wallet, there is no need to unlock first and that the timer can easily be avoided

Indeed, this is a known (and problematic) issue 😬. Fix should be packed with next release 😌.

**Comment by trstbdrt** [comment]
Thanks for the answer :)
Also, I would like to suggest something in case we "forgot" the PIN code or Password of the wallet. If you try 5 times and fail, in the same screen as the timer, we could imagine a button like "re-encode my 24 words". and then you could set up a new PIN/password.

That would avoid that the users need to uninstall and reinstall the app. What do you think?

**Comment by Chralu** [comment]
> Thanks for the answer :) Also, I would like to suggest something in case we "forgot" the PIN code or Password of the wallet. If you try 5 times and fail, in the same screen as the timer, we could imagine a button like "re-encode my 24 words". and then you could set up a new PIN/password.
> 
> That would avoid that the users need to uninstall and reinstall the app. What do you think?

Totally agree. This [is in the pipe too](https://github.com/archethic-foundation/archethic-wallet/issues/950) 😇

**Comment by trstbdrt** [comment]
Good! In fact I am just checking all the suggestions I did to Sylvain few weeks ago, but didn't check if cases were already created or not :)

**Comment by trstbdrt** [comment]
I guess there are also issues for those:

-Add a button to manually lock the wallet.
-If the aeSwap is launched from the wallet, it seems that the fact the we "move" in aeSwap is not detected, then the wallet will automatically lock once the time is up, even if we were doing things in it.
- in the Auto-Lock menu, not sure what "instantly" means? It doesn't seems to instantly lock...

**Comment by Chralu** [comment]
> I guess there are also issues for those:
> 
> -Add a button to manually lock the wallet. -If the aeSwap is launched from the wallet, it seems that the fact the we "move" in aeSwap is not detected, then the wallet will automatically lock once the time is up, even if we were doing things in it.
> 
>     * in the Auto-Lock menu, not sure what "instantly" means? It doesn't seems to instantly lock...

Hi @trstbdrt indeed, there are issues for those. 

You can find all issues [here](https://github.com/archethic-foundation/archethic-wallet/issues).
And we created [a milestone to regroup issues to fix in the next release](https://github.com/archethic-foundation/archethic-wallet/milestone/2).

In order to keep a clear conversation, please use dedicated issues comment threads to add suggestions.
If issues do not exist yet, feel free to create them. 
This would be a huge help 🙏

If you need for help in that process, contact us on Telegram or Discord.

**Comment by Chralu** [comment]
FYI, option **Setting Lock on startup** won't be added. 

Due to the introduction of a more secured storage system, user will always have to unlock the application when it starts from zero.

**Comment by quentin-legraverend** [comment]
> FYI, option **Setting Lock on startup** won't be added.
> 
> Due to the introduction of a more secured storage system, user will always have to unlock the application when it starts from zero.

That's even better IMHO.
Will that be the case on both mobile and desktop?

**Comment by Chralu** [comment]
> > FYI, option **Setting Lock on startup** won't be added.
> > Due to the introduction of a more secured storage system, user will always have to unlock the application when it starts from zero.
> 
> That's even better IMHO. Will that be the case on both mobile and desktop?

Yes. This behavior is platform agnostic.

**Comment by n0uki63** [comment]
Good issue
