### ISSUE TITLE
AWCWebview crashes when networks fails

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#957]
### Describe the problem you discovered

# Steps to reproduce issue

- From AEWallet mobile
- Enable phone airplane mode
- Go to AESwap in webview
- ==> Loading fails
- Navigate back to AEWallet home
- Disable phone airplane mode
- Go to AESwap in webview
- ==> It is still broken. User has to uninstall/reinstall AEWallet to get it working again

**Comment by redDwarf03** [comment]
it works with version > 2.3.9
