### ISSUE TITLE
WebExtension : Wallet window size should not be increased by users

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#968]
### Describe the solution you'd like

Wallet extension does not display nice in a huge window. To prevent that, we should disable window size increase.

It would be great to allow Window size decrease for users with small screens.

**Comment by Chralu** [comment]
Duplicate of #974

**Comment by redDwarf03** [comment]
Sorry. so i updated milestone

**Comment by Chralu** [comment]
No worries. It's alright to me to put this in the milestone.

My previous remark was a bad joke actually. Thanks for your help 🙏
