### ISSUE TITLE
Extension chrome - Block window widening 

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#974]
### Describe the problem you discovered

Do not allow the possibility of enlarging the window. However, leave the option to reduce it if possible

**Comment by Chralu** [comment]
Duplicate of #968

**Comment by Chralu** [comment]
@redDwarf03 There actually is no way to do this in modern web browser.

Maybe the best move is to cap the application width whatever the platform.

**Comment by redDwarf03** [comment]
> @redDwarf03 There actually is no way to do this in modern web browser.
> 
> Maybe the best move is to cap the application width whatever the platform.

agree

**Comment by Chralu** [comment]
Issue on wide mobile phones (iPhone 15 Pro Max) : the screen is wider than max app width.
![simulator_screenshot_A2CF6F35-8618-421F-B2AA-385D8EFD39E3](https://github.com/archethic-foundation/archethic-wallet/assets/375723/683cd76f-1f67-4243-9c45-11f927824711)
