### ISSUE TITLE
Message about jailbreak disappears too quickly

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#989]
when i launch in mobile mode the app, after fill the pin, the duration of the displaying of message about jailbreak is too short

_Originally posted by @redDwarf03 in https://github.com/archethic-foundation/archethic-wallet/pull/981#pullrequestreview-2112189861_

**Comment by redDwarf03** [comment]
tests ok for me with https://github.com/archethic-foundation/archethic-wallet/pull/981
